name: metrics

on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run the workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: Metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: wolvfyxmoon-ornery
          template: classic
          base: header, activity, community, repositories, metadata
          commits_authoring: wolvfyxmoon-ornery
          config_octicon: yes
          config_timezone: Asia/Kolkata
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 5
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: S
          plugin_calendar: yes
          plugin_calendar_limit: 3
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          plugin_habits: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_music: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: random
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 14
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_languages: yes
          plugin_languages_aliases: javascript, java, react, Python, Html, Css, Typescript
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 9
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_other: yes
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 8
          plugin_lines_sections: base
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
          plugin_pagespeed_screenshot: yes
          plugin_pagespeed_url: "https://github.com/wolvfyxmoon-ornery.github.io"
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_thanks: reallyakera
          plugin_people_types: followers, following
          plugin_tweets: yes
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          repositories_forks: yes
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          plugin_skyline: yes
          plugin_skyline_compatibility: yes
          plugin_skyline_year: 2021
          plugin_skyline_frames: 120
          plugin_reactions_days: 14
          plugin_reactions_details: percentage
          plugin_notable: yes
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 15
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_sample: 2
          plugin_starlists: yes
          plugin_starlists_limit: 2
          plugin_starlists_limit_languages: 8
          plugin_starlists_limit_repositories: 2
          plugin_starlists_shuffle_repositories: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_support: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_tweets_attachments: yes
          plugin_tweets_limit: 3
          plugin_tweets_user: MukulSh33946252
          plugin_fortune: yes
          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list, about
          plugin_gists: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_followup_indepth: yes
          plugin_posts: yes
          plugin_posts_source: dev.to
          plugin_posts_limit: 2
          plugin_posts_descriptions: yes
          plugin_posts_covers: yes
          plugin_languages_details: bytes-size, percentage
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent

      - name: Update README.md
        run: |
          echo '![Metrics](Metrics.svg)' > README.md
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}